title: "Boda de Mercedes & Pablo"
description: "Nuestra boda, fotos, RSVP y todo lo que necesitas para el gran d√≠a"
url: "https://pablovicentem.github.io/Boda-Mercedes-y-Pablo"
theme: minima
plugins:
  - jekyll-seo-tag
